@startuml
class User {
    +username: String
    +email: String
    +password: String
    +role: Number
    +classId: ObjectId
    +groupId: ObjectId
    +status: String
    +isLeader: Boolean
    +timestamps: Boolean
}

class UserDAO {
    +findUser(criteria: {email: String}): User
}

class EmailService {
    +sendEmail(details: {recipient_email: String, OTP: Number}): Promise
}

class OTPStore {
    +generateOTP(): Number
}

class UserController {
    +forgotPassword(req: Request, res: Response): Promise<void>
}

class Database {
    <<Database>>
    +Query(query: Object): Object
}

UserController --> UserDAO : Uses
UserDAO --> User : Interacts with
UserDAO --> Database : Queries
UserController --> OTPStore : Generates OTP
UserController --> EmailService : Sends email
@enduml
